### ISSUE TITLE
PyLNP.exe doesn't launch on Windows 

### ISSUE THREAD

**Issue by ghost** [PeridexisErrant/starter-pack#18]
So, replacing the r06 PyLNP.exe with the r05 PyLNP.exe allows the launcher to run, but when trying to start the game you get this error (sorry for the comment spam)

![image](https://user-images.githubusercontent.com/7612785/27273137-84674096-5482-11e7-9431-4905f65b475d.png)

**Comment by PeridexisErrant** [comment]
This is an [upstream bug in PyLNP 0.12b for Windows](http://www.bay12forums.com/smf/index.php?topic=140808.msg7489409#msg7489409), which is fixed in 0.12c - I'll upload a new pack soon.
