### ISSUE TITLE
Filename for Armok Vision is Incorrect on Linux

### ISSUE THREAD

**Issue by bashterm** [PeridexisErrant/starter-pack#19]
The Armok Vision binary is called 'Armok Vision Linux.x86_64' on Linux, but is referred to as 'Armok Vision.x86_64' in the code.

**Comment by PeridexisErrant** [comment]
That's an issue for Armok Vision, not this pack-building tool, because AV bundles it's own manifest file.

**Comment by lethosor** [comment]
Do you use that manifest here?
