### ISSUE TITLE
Wrong memory layout format for DT for DF 44.03

### ISSUE THREAD

**Issue by shnaps** [PeridexisErrant/starter-pack#21]
Wrong memory layout file format for the latest version of Therapist.

**Comment by lethosor** [comment]
Are you sure you reported this in the right place? The last commits in this repo were for 0.44.02.

**Comment by shnaps** [comment]
Yep. I think so. 
Cloned repo and tried to compile for 44.03. Everything works except DT memory layout file format. Made little fix for it. But I don't know - should I create pr or just report issue.

**Comment by lethosor** [comment]
I'd make a PR if you have a fix. What's the issue, anyway? Is "wrong memory layout format" the only message?

**Comment by shnaps** [comment]
Seems like DT changed file format for memory layouts.
Now layout is v0.44.03_graphics_win64.ini
Previous is v0.44.02_x64_graphics.ini

**Comment by lethosor** [comment]
Ok, so it's the file name, not the format of the contents. Yeah, Clement (the new maintainer) changed it for consistency with the other platforms' memory layouts.

**Comment by shnaps** [comment]
Oh, yes, file name. My fail, lol
