### ISSUE TITLE
Pack is getting flagged as malware

### ISSUE THREAD

**Issue by T00mm** [PeridexisErrant/starter-pack#28]
Noticed that the latest build is getting flagged as Malware by a couple of anti-virus vendors. (Sophos did for my PC).

`Generic ML PUA detected at C:\Users\Tom\Desktop\Df\Starter Pack Launcher (PyLNP).exe`

VirusTotal shows others have the same issue

ZipFile

https://www.virustotal.com/gui/file/911fb049de1b115d308bb152f3518120f6e23d1b71d9cce8a62b66cfc198d2d1/detection

Starter Pack Launcher (PyLNP).exe

https://www.virustotal.com/gui/file/5d4ae798961baa4b3bf1eb3d6df30ac411b289b4ce9d9e781e2c057aafede5f2/detection

**Comment by PeridexisErrant** [comment]
Unfortunately there's not much we can do about this - it's usually an over-broad match on part of the python-to-executable built tooling 😕
